# Generated by Django 4.2 on 2023-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GallaryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('File', models.FileField(upload_to='file/%y')),
                ('time', models.DateField()),
            ],
            options={
                'ordering': ('-mediaId',),
            },
        ),
    ]
